server:
  port: 8081
#  context-path: /api/v1/message

spring:
  application:
    name: tag-service
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat


security.oauth2.resource.token-info-uri: http://localhost:9999/uaa/oauth/check_token
security.oauth2.client.client-id: demo
security.oauth2.client.client-secret: demo



#auth-server: http://localhost:9999/uaa
#security:
#  basic:
#    enabled: false
#  oauth2:
#    client:
#      client-id: demo
#      client-secret: demo
#      access-token-uri: ${auth-server}/oauth/token
#      user-authorization-uri: ${auth-server}/oauth/authorize
#      scope: read, write
#    resource:
#      token-info-uri: ${auth-server}/oauth/check_token
#      user-info-uri: ${auth-server}/user
proxy:
  auth:
    load-balanced: true
logging:
  level:
    org.springframework.security: DEBUG


